### ISSUE TITLE
Calendar for The Ordinariate of the Chair of St. Peter

### ISSUE THREAD

**Issue by RussellHaley** [igneus/calendarium-romanum#44]
Hi, 

I'm a member of The Ordinariate of The Chair of St. Peter. I wanted to automate our church calendar on our new website. I'm not sure about the specific differences between the Roman Calendar and the Ordinariate Calendar as of yet but I assume I will need to change the universal-en.txt data file and possibly make modifications to calendarium-romanum/lib/calendarium-romanum/temporale.rb.

Should I be looking at implementing the new Calendar in this project, or the Church Calendar API? I don't see a corresponding temporale.rb in the CC API project. 

Any advice you could offer would be great.

**Comment by igneus** [comment]
Hi,

I must admit having no prior knowledge of the Anglican ordinariates' liturgy and calendar(s). Trying to find some kind of a "formal specification" of the calendar, I found [this](http://prelaturaspersonales.org/wp-content/uploads/2012/02/Calendar_for_Ordinariate.pdf) - I am, however, not at all sure how un/official this document is, by whom it was prepared and how exact it is.

If it describes the calendar correctly, the calendar system is very similar to the current Roman one, but there are some differences in Sunday counting and there seems not to exist a single "Ordinary Time", but instead two liturgical seasons (after Epiphany, after Trinity) spanning the same periods of time. This would mean that in order to implement the ordinariate's calendar, you can mostly use this gem's code. You will have to prepare a [sanctorale data file](https://github.com/igneus/calendarium-romanum/tree/master/data) and a class extending `Temporale` and implementing the ordinariate's specifics (liturgical seasons not known to the Roman calendar, Sunday numbering, custom movable feasts if there are any differences).

```ruby
require 'calendarium-romanum'

module OrdinariateCalendar
  class Temporale < ::CalendariumRomanum::Temporale
    # most of the hard work comes here
  end
end

year = 2019
sanctorale = CalendariumRomanum::SanctoraleLoader.new.load_from_file 'path/to/your/ordinariate_chair_st_peter.txt'
temporale = OrdinariateCalendar::Temporale.new(year)
calendar = CalendariumRomanum::Calendar.new(year, sanctorale, temporale)
```

In the custom `Temporale` implementation you will have to
override all the public season-computing methods:

- season
- season_beginning
- season_week

then the protected method `prepare_solemnities` (which computes dates of all movable celebrations, not only solemnities) and possibly also methods `ferial` and `sunday`, in order to correctly handle ferial and Sunday naming for the seasons unknown to the Roman calendar.

Feel free to ask questions along the way. I suspect the process could inspire some modifications to `calendarium-romanum` itself, making it more suitable for extensions like this.

**Comment by RussellHaley** [comment]
Thank you, I look forward to drilling in.

**Comment by RussellHaley** [comment]
I used the ordinariate file you found and modified the solemnities file universal-en.txt. I also added an ordinariate-temporal.rb file that just calls super. I added a file called cmds.rb to run the commands as you specified them. 
https://github.com/RussellHaley/calendarium-romanum/commit/0db980bd5d28be228fd5dfc7f044711dda4743c1

I am getting an error when reading the solemnities files. I get the same error with universal-en.txt and ordinariate-en.txt. The error occurs before any changes that I made (other than the title). Thoughts?

```
ruby cmds.rb 
Traceback (most recent call last):
        6: from cmds.rb:5:in `<main>'
        5: from /var/lib/gems/2.5.0/gems/calendarium-romanum-0.6.0/lib/calendarium-romanum/sanctorale_loader.rb:82:in `load_from_file'
        4: from /var/lib/gems/2.5.0/gems/calendarium-romanum-0.6.0/lib/calendarium-romanum/sanctorale_loader.rb:35:in `load'
        3: from /var/lib/gems/2.5.0/gems/calendarium-romanum-0.6.0/lib/calendarium-romanum/sanctorale_loader.rb:35:in `with_index'
        2: from /var/lib/gems/2.5.0/gems/calendarium-romanum-0.6.0/lib/calendarium-romanum/sanctorale_loader.rb:35:in `each_line'
        1: from /var/lib/gems/2.5.0/gems/calendarium-romanum-0.6.0/lib/calendarium-romanum/sanctorale_loader.rb:63:in `block in load'
/var/lib/gems/2.5.0/gems/calendarium-romanum-0.6.0/lib/calendarium-romanum/sanctorale_loader.rb:66:in `rescue in block in load': L8: Syntax error, line skipped '2 m basil_gregory : Saints Basil the Great and Gregory Nazianzen, bishops and doctors' (CalendariumRomanum::InvalidDataError)
```

**Comment by igneus** [comment]
The problem is you have installed calendarium-romanum version 0.6.0 (which gets used - see the backtrace), but the sanctorale data file is in a newer format (with machine-readable feast identifiers added), prepared for the not yet released version 0.7.0.

You can remedy this by explicitly telling Ruby to load calendarium-romanum source you have checked out from git:
(`cd` in the project's root directory and then) `ruby -I lib cmds.rb`

**Comment by RussellHaley** [comment]
Ah, yes, I see that now. Ha ha. Thanks!

**Comment by RussellHaley** [comment]
You sir, are a brilliant developer. I've never written a line of ruby in my life and in a few short hours I was able to largely implement the Ordinariate Calendar. Your code is concise and well organized and wonderfully expressive. I was - not two weeks ago - railing against the pitfalls of Object Oriented Design and you, my good man, have made me eat my hat. 

Here is what I have so far:
https://github.com/RussellHaley/calendarium-romanum/compare/8209e2055..d7e0f4b79

Outstanding Issues:
- The Penticostal Octave comes out as the eighth week of Easter
- There are some celebrations that I need to add. I penciled them into the celebration factory in brackets with the week they are in (e.g. Septuagesima).  
- There are some other items that I still need to decipher in the Ordinariate calendar. 

Vivat Jesus,
Russell

**Comment by igneus** [comment]
Had you ever worked with some other codebases I've written, you would probably be more cautious calling me a "brilliant developer" and rather say something like _"`calendarium-romanum` is definitely one of the better pieces of software you've ever written,"_ which I would wholeheartedly agree with :wink:
It should also be noted that a great deal of the code being "wonderfully expressive" is owed to the Ruby language, which is known both for extraordinary expressiveness and friendliness/accessibility to beginners.

Having read through what you have so far I have one suggestion: implementing (or modifying) a library like this (which consists mostly of pure computation, i.e. is almost free of side-effects like interaction with a database and the like) is a great playground for exercising [TDD](https://en.wikipedia.org/wiki/Test-driven_development). `calendarium-romanum` has (or at least I believe it has) good coverage by [RSpec](https://rspec.info/) tests which you can build upon. In the commit history you will find numerous examples of a commit implementing a small new feature (or fixing a bug) and consisting of a test (which originally failed) and code which makes the test pass - see e.g. https://github.com/igneus/calendarium-romanum/commit/2f867bc1971c6f94f53fb5f3b4a5dd6be605565a https://github.com/igneus/calendarium-romanum/commit/398e6394573c4dac9b235dc987c632fefb07df28 https://github.com/igneus/calendarium-romanum/commit/6b77665d89cf1ed7de523c6b8a98b1b0a37e4886 https://github.com/igneus/calendarium-romanum/commit/8c52ad8525c5d2c3349e44e8ea01f04a7d1372fb - and many more. Working in steps like this has numerous [advantages](https://en.wikipedia.org/wiki/Test-driven_development#Benefits).

(Tip: in the TDD cycle you will want the tests to run fast. In order to skip a particularly slow subset of the test suite - tests of the `calendariumrom` command - run tests like `rspec --exclude-pattern spec/cli_spec.rb`)

**Comment by RussellHaley** [comment]
Thank you, unit tests are an excellent suggestion. 

So, funny story: Someone reminded me that I actually PURCHASED a calendar from the parish earlier in the year! So I have an accurate reference point to test with (and build unit tests) going forward.

I'm trying to add some celebrations: septuagesima, sexagesima, quinquagesima. 

I've added them in the temporale/celebrations_factory.rb:

```ruby
      celebration(:septuagesima, Ranks::SOLEMNITY_GENERAL)
      celebration(:sexagesima, Ranks::SOLEMNITY_GENERAL)
      celebration(:quinquagesima, Ranks::SOLEMNITY_GENERAL)
```
I've added them to the temporale/dates.rb:

```ruby

      def self.septuagesima(year)
         self.ash_wednesday(year) - 17
      end
      
      def self.sexagesima(year)
          self.ash_wednesday(year) - 10
      end
      
      def self.quinquagesima(year)
             self.ash_wednesday(year) - 3 
      end
      
      def self.ash_wednesday(year)
        easter_sunday(year) - (6 * WEEK + 4)
      end
```

and I've added them to the config/locales/en.yml file:

```ruby

    time_after_epiphany:
      ferial: '%{weekday}, %{week} week after Epiphany'
      septuagesima: 'Septuagesima'
      sexagesima: 'Sexagesima'
      quinquagesima: 'Quinquagesima'
      sunday: '%{week} Sunday after Epiphany'      
```

When I run the date of Qunquagesima which was on calendar year 2019, 03, 03:

```
russellh@pureos:~/git/calendarium-romanum$ ruby -I lib cmds.rb 2018 3 3
Calendar Date: 2019-03-03
9th Sunday after Epiphany
#<CalendariumRomanum::Day @date=2019-03-03 @season=#<CalendariumRomanum::Season time_after_epiphany> @season_week=9 celebrations=[#<CalendariumRomanum::Celebration @title="9th Sunday after Epiphany" @rank=#<CalendariumRomanum::Rank @priority=2.6 desc="Unprivileged Sundays"> @colour=#<CalendariumRomanum::Colour rose> symbol=nil date=nil cycle=:temporale>] vespers=nil>
```
I have test code in ordinariate-temporale.rb (sunday) that shows it "should be working" :

```ruby
if date == (ash_wednesday - 3)
              puts "Ash wednesay: " + ash_wednesday.to_s
              puts "Quinquagesima"
          end
```
which outputs:

```
russellh@pureos:~/git/calendarium-romanum$ ruby -I lib cmds.rb 2018 3 3
Ash wednesay: 2019-03-06
Quinquagesima
Calendar Date: 2019-03-03
```
Any thoughts as to what I've missed?

**Comment by igneus** [comment]
For reference: example of adding a single new temporale celebration is https://github.com/igneus/calendarium-romanum/commit/0a5c820239697a4a6ba964a186af32aafcc82ec4

I don't see your complete code, so I'm not 100% sure, but considering what you show in the snippets and what you do not, I probably see the reason why your temporale on the given day doesn't produce the desired celebration:
All temporale feasts of the given year are built on `Temporale` initialization, in `Temporale#prepare_solemnities`. It iterates through `Temporale.celebrations`, computes and stores date for each entry. But your pre-Lenten Sundays are not in this list.

**Comment by RussellHaley** [comment]
Thank you!

**Comment by RussellHaley** [comment]
Rogation Days are the three days following the Sixth Sunday of Easter. Do you have any suggestions how I would accomplish that in CR?

**Comment by igneus** [comment]
I've no idea what's their rank in the Ordinariate calendar, but depending on the rank they would be handled either by `Temporale#prepare_solemnities` or `#ferial`.

**Comment by igneus** [comment]
Closing due to inactivity, feel free to reopen if needed.
